on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vakirepo.azurecr.io
        username: ${{ secrets.acr_vakirepo_username }}
        password: ${{ secrets.acr_vakirepo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t vakirepo.azurecr.io/vakicluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push vakirepo.azurecr.io/vakicluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vakicluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep python_apps | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace python_apps`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: python_apps
        container-registry-url: vakirepo.azurecr.io
        container-registry-username: ${{ secrets.acr_vakirepo_username }}
        container-registry-password: ${{ secrets.acr_vakirepo_password }}
        secret-name: vakiclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: python_apps
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          vakirepo.azurecr.io/vakicluster:${{ github.sha }}
        imagepullsecrets: |
          vakiclusterdockerauth
